### ISSUE TITLE
User can see their car

### ISSUE THREAD

**Issue by dennisliu9** [dennisliu9/driving-game#1]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [x] Create a green background to be the ground the car drives on
- [x] Insert car as an `img` element
- [x] Scale car if necesssary
