### ISSUE TITLE
User can turn their car

### ISSUE THREAD

**Issue by dennisliu9** [dennisliu9/driving-game#2]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [x] Create a data object that stores the car orientation, defaulted to east
- [ ] Create CSS classes for each orientation with the `rotate` transformation function and test that applying them gives the correct orientation
- [x] Create an event listener on the document for `keydown` events
- [x] Determine what values are given when arrow keys are pressed
- [x] Query the DOM tree for the car
- [x] Write a function that takes in the keys detected by the `keydown` event and sets the car orientation value in the data object
- [x] Have the function update the car's orientation based on the value in the data object by applying the correct CSS class
- [x] Add a `transition` to the car so that the car appears to rotate into the next orientation

**Comment by dennisliu9** [comment]
### Provided Hints
* Create a simple data model that includes which way the car is facing, (north, south, east, or west).
* Listen for 'keydown' events on the document.

**Comment by dennisliu9** [comment]
Modified plan to turn car left or right with the left or right arrow keys. The up arrow key is reserved for moving the car forward, and the down arrow key does a cool spinning trick that points the car in the opposite direction. Hopefully this is more adaptable for future features!

**Comment by dennisliu9** [comment]
![issue-2-turn-car_solution](https://user-images.githubusercontent.com/21215658/172962805-eb55639c-d17d-4b70-917c-4db0c15bdc0b.gif)
