### ISSUE TITLE
User can start their car

### ISSUE THREAD

**Issue by dennisliu9** [dennisliu9/driving-game#3]
## 💰 Motivation

It's a driving game, duh!

## 📐 Plan

Move the car a few pixels every 16 milliseconds when the user presses space.

## ✅ Task List

- [x] Under the event listener for `keydown`, check for the spacebar being pressed.
- [x] Write a function to translate the car in the X direction a few pixels.
- [x] Set an interval to execute the car translation function every 16 milliseconds.
- [x] Check that the interval works as expected when the car starts in various orientations.
- [x] Check that the interval continues to work when the car's orientation changes in the middle of translating.

**Comment by dennisliu9** [comment]
![issue-3-start-car_solution](https://user-images.githubusercontent.com/21215658/172995761-a04992ad-78c9-4f25-b12b-0978abe41aa6.gif)
