### ISSUE TITLE
User can stop their car

### ISSUE THREAD

**Issue by dennisliu9** [dennisliu9/driving-game#4]
## 💰 Motivation

If the user cannot stop their car, it goes off the page.

## 📐 Plan

Stop the car if the user presses ~~space again~~ the enter key. Pressing space multiple times increases the speed, and we gotta go fast!!

## ✅ Task List

- [x] Create an array that stores the interval ids for each interval that gets created with the spacebar/up arrow.
- [x] Add a check in the `keydown` event listener for the Enter key.
- [x] Under the Enter key check, loop through the array of interval ids and clear all intervals.

**Comment by dennisliu9** [comment]
![issue-4-stop-car_solution](https://user-images.githubusercontent.com/21215658/173001762-d6f89773-2c7d-428f-9271-97ccde91d95e.gif)
